// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using c_sharp_grad_backend.Data;

namespace c_sharp_grad_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200526143241_NewCell")]
    partial class NewCell
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("c_sharp_grad_backend.Models.Donations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraTwo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TableDonations");
                });

            modelBuilder.Entity("c_sharp_grad_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TableUsers");
                });

            modelBuilder.Entity("c_sharp_grad_backend.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressTwo")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AvatarOne")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AvatarThree")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AvatarTwo")
                        .HasColumnType("BLOB");

                    b.Property<string>("CVV")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationOnCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraPropFour")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraPropOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraPropThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraPropTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOnCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TableUserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
